from _typeshed import Incomplete

durations: Incomplete

def tostring(dur, dots: int = ..., factor: int = ...): ...
def base_scaling(tokens): ...
def base_scaling_string(duration): ...
def fraction(tokens): ...
def fraction_string(duration): ...
def format_fraction(value): ...
