from _typeshed import Incomplete

class Indenter:
    indent_tabs: bool
    indent_width: int
    def __init__(self) -> None: ...
    def indent(self, cursor, indent_blank_lines: bool = ...) -> None: ...
    def increase_indent(self, cursor) -> None: ...
    def decrease_indent(self, cursor) -> None: ...
    def get_indent(self, document, block): ...
    def compute_indent(self, document, block): ...

class Line:
    indent: bool
    isblank: bool
    dedenters_start: int
    dedenters_end: int
    indenters: Incomplete
    def __init__(self, document, block) -> None: ...
    def is_special_scheme_keyword(self, token): ...
