def replace_rest(cursor, replace_token) -> None: ...
def replace_fmrest(cursor, replace_token) -> None: ...
def replace_spacer(cursor, replace_token) -> None: ...
def replace_restcomm(cursor, replace_token) -> None: ...
