from _typeshed import Incomplete

known_commands: Incomplete

class _command:
    def __init__(self) -> None: ...
    def run(self, opts, data) -> None: ...

class set_variable(_command):
    def __init__(self, arg) -> None: ...
    def run(self, opts, data) -> None: ...

class _info_command(_command):
    def run(self, opts, data) -> None: ...
    def get_info(self, info) -> None: ...

class _edit_command(_command):
    def run(self, opts, data) -> None: ...
    def edit(self, opts, cursor) -> None: ...

class _export_command(_command):
    def run(self, opts, data) -> None: ...
    def export(self, opts, cursor, exports) -> None: ...

class mode(_info_command):
    def get_info(self, info): ...

class version(_info_command):
    def get_info(self, info): ...

class language(_info_command):
    def get_info(self, info): ...

class indent(_edit_command):
    def indenter(self, opts): ...
    def edit(self, opts, cursor) -> None: ...

class reformat(indent):
    def edit(self, opts, cursor) -> None: ...

class translate(_edit_command):
    language: Incomplete
    def __init__(self, language) -> None: ...
    def edit(self, opts, cursor) -> None: ...

class transpose(_edit_command):
    def __init__(self, arg) -> None: ...
    def edit(self, opts, cursor) -> None: ...

class rel2abs(_edit_command):
    def edit(self, opts, cursor) -> None: ...

class abs2rel(_edit_command):
    def edit(self, opts, cursor) -> None: ...

class musicxml(_export_command):
    def export(self, opts, cursor, exports): ...

class highlight(_export_command):
    def export(self, opts, cursor, exports): ...
