from _typeshed import Incomplete
from http.server import BaseHTTPRequestHandler

default_opts: Incomplete

class RequestHandler(BaseHTTPRequestHandler):
    def create_command(self, cmd): ...
    def process_options(self, opts): ...
    def process_json_request(self, request): ...
    def read_json_request(self): ...
    def do_POST(self) -> None: ...
