from . import handler as handler, options as options

def usage() -> None: ...
def usage_short() -> None: ...
def version() -> None: ...
def die(message) -> None: ...
def parse_command_line(): ...
def main(): ...
