from .. import slexer as slexer
from _typeshed import Incomplete

class Token(slexer.Token): ...

class patternproperty:
    func: Incomplete
    def __init__(self, func) -> None: ...
    rx: Incomplete
    def __get__(self, instance, owner): ...

class Unparsed(Token): ...

class Item(Token):
    def update_state(self, state) -> None: ...

class Leaver(Token):
    def update_state(self, state) -> None: ...

class Space(Token):
    rx: str

class Newline(Space):
    rx: str

class Comment(Token): ...
class LineComment(Comment): ...
class BlockComment(Comment): ...
class BlockCommentStart(BlockComment): ...
class BlockCommentEnd(BlockComment): ...
class String(Token): ...
class StringStart(String): ...
class StringEnd(String): ...
class Character(Token): ...
class Numeric(Token): ...
class Error(Token): ...

class MatchStart:
    matchname: str

class MatchEnd:
    matchname: str

class Indent: ...
class Dedent: ...
